model:
  base_learning_rate: 4.5e-7
  target: net2net.models.flows.flow.Net2NetFlow
  params:
    first_stage_key: "image"
    cond_stage_key: "class"
    flow_config:
      target: net2net.modules.flow.flatflow.ConditionalFlatCouplingFlow
      params:
        conditioning_dim: 4
        embedding_dim: 10
        conditioning_depth: 2
        n_flows: 20
        in_channels: 128
        hidden_dim: 1024
        hidden_depth: 2
        activation: "none"
        conditioner_use_bn: True

    cond_stage_config:
      target: net2net.modules.labels.model.Labelator
      params:
        num_classes: 4
        as_one_hot: True

    first_stage_config:
      target: net2net.models.autoencoder.BigAE
      params:
        ckpt_path: "logs/2021-11-10T22-02-01_200_epochs/checkpoints/last.ckpt"
        encoder_config:
          target: net2net.modules.autoencoder.encoder.ResnetEncoder
          params:
            in_channels: 3
            in_size: 227
            pretrained: true
            type: resnet101
            z_dim: 128

        decoder_config:
          target: net2net.modules.autoencoder.decoder.BigGANDecoderWrapper
          params:
            z_dim: 128
            in_size: 256
            use_actnorm_in_dec: true

        loss_config:
          target: net2net.modules.autoencoder.loss.DummyLoss

data:
  target: translation.DataModuleFromConfig
  params:
    batch_size: 4
    train:
      target: net2net.data.pacs.PACSTrain
      params:
        size: 227
    validation:
      target: net2net.data.pacs.PACSValidation
      params:
        size: 227
