model:
  base_learning_rate: 4.5e-6
  target: net2net.models.flows.flow.Net2NetFlow
  params:
    ckpt_path: "logs/2021-12-03T18-07-45_512_net2net_2/checkpoints/epoch=000958.ckpt"
    first_stage_key: "image"
    cond_stage_key: "class"
    flow_config:
      target: net2net.modules.flow.flatflow.ConditionalFlatCouplingFlow
      params:
        conditioning_dim: 4
        embedding_dim: 10
        conditioning_depth: 2
        n_flows: 20
        in_channels: 512
        hidden_dim: 1024
        hidden_depth: 2
        activation: "none"
        conditioner_use_bn: True

    cond_stage_config:
      target: net2net.modules.labels.model.Labelator
      params:
        num_classes: 4
        as_one_hot: True

    first_stage_config:
      target: net2net.models.autoencoder.BigAE
      params:
        ckpt_path: "logs/2021-11-30T22-23-36_512_pretrained_continue/checkpoints/epoch=000083.ckpt"
        encoder_config:
          target: net2net.modules.autoencoder.encoder.ResnetEncoder
          params:
            in_channels: 3
            in_size: 256
            pretrained: false
            type: resnet101
            z_dim: 512

        decoder_config:
          target: net2net.modules.autoencoder.decoder.BigGANDecoderWrapper
          params:
            z_dim: 512
            in_size: 256
            use_actnorm_in_dec: true

        loss_config:
          target: net2net.modules.autoencoder.loss.DummyLoss

data:
  target: translation.DataModuleFromConfig
  params:
    batch_size: 8
    train:
      target: net2net.data.pacs.PACSTrain
    validation:
      target: net2net.data.pacs.PACSValidation
