model:
  base_learning_rate: 4.5e-6
  target: net2net.models.classifier.Classifier
  params:
    input_height: 256
    latent_dim: 256

data:
  target: translation.DataModuleFromConfig
  params:
    batch_size: 15
    train:
      target: net2net.data.pacs.PACSTrain
      params:
        domains:
          - "photo"
          - "art_painting"
          - "sketch"
        contents:
          - "dog"
          - "elephant"
          - "giraffe"
          - "guitar"
          - "horse"
          - "house"
          - "person"
    validation:
      target: net2net.data.pacs.PACSValidation
      params:
        domains:
          - "photo"
          - "art_painting"
          - "sketch"
        contents:
          - "dog"
          - "elephant"
          - "giraffe"
          - "guitar"
          - "horse"
          - "house"
          - "person"
