model:
  base_learning_rate: 4.5e-6
  target: net2net.models.classifier.Classifier
  params:
    input_height: 256
    latent_dim: 256

data:
  target: translation.DataModuleFromConfig
  params:
    batch_size: 15
    train:
      target: net2net.data.pacs.PACSTrain
    validation:
      target: net2net.data.pacs.PACSValidation
