model:
  base_learning_rate: 4.5e-6
  target: net2net.models.classifier.Classifier
  params:
    loss_config:
      target: net2net.modules.classifier.loss.ClassifierLoss
      params:
        disc_start: 75001  # change

    encoder_config:
      target: net2net.modules.autoencoder.encoder.ResnetEncoder
      params:
        in_channels: 3
        in_size: 256
        pretrained: false
        type: resnet101
        z_dim: 128

    decoder_config:
      target: net2net.modules.autoencoder.decoder.BigGANDecoderWrapper
      params:
        z_dim: 128
        in_size: 256
        use_actnorm_in_dec: true


data:
  target: translation.DataModuleFromConfig
  params:
    batch_size: 15
    train:
      target: net2net.data.pacsgen.PACSGeneratedTrain
    validation:
      target: net2net.data.pacsgen.PACSGeneratedValidation
